[package]
name = "leetcode_rust"
version = "0.1.0"
license = "MIT"
edition = "2021"

[dev-dependencies]
criterion = "0.7"

[[bench]]
name = "p1814"
harness = false

[[bench]]
name = "p1910"
harness = false

[[bench]]
name = "p1910_memory"
harness = false
